version: '3'
services:
  telnet_server:
    image: ubuntu-ssh:22.04
    volumes:
    - ../:/root/ltVPN
    networks:
      internal_network:
        ipv4_address: 192.168.12.2
    privileged: true

  vpn_client1:
    image: ubuntu-ssh:22.04
    volumes:
    - ../:/root/ltVPN
    networks:
      external_network:
        ipv4_address: 10.12.1.2
    privileged: true

  vpn_client2:
    image: ubuntu-ssh:22.04
    volumes:
    - ../:/root/ltVPN
    networks:
      external_network:
        ipv4_address: 10.12.1.3
    privileged: true

  vpn_client3:
    image: ubuntu-ssh:22.04
    volumes:
    - ../:/root/ltVPN
    networks:
      external_network:
        ipv4_address: 10.12.1.4
    privileged: true

  vpn_client4:
    image: ubuntu-ssh:22.04
    volumes:
    - ../:/root/ltVPN
    networks:
      external_network:
        ipv4_address: 10.12.1.5
    privileged: true

networks:
  internal_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.12.0/24
          gateway: 192.168.12.1

  external_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.12.1.0/24
          gateway: 10.12.1.1
